import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    backgroundColor: "white",
  },
  backBtn: {
    padding: 4,
  },
  headerTitleWrap: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1e293b",
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  tabsWrapper: {
    flexDirection: "row",
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingBottom: 10,
    gap: 12,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
    backgroundColor: "#f1f5f9",
  },
  tabBtnActive: {
    backgroundColor: "#0284c7",
  },
  tabBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#64748b",
  },
  tabBtnTextActive: {
    color: "white",
  },
  tabContent: {
    flex: 1,
    padding: 20,
  },
  mainCard: {
    backgroundColor: "white",
    borderRadius: 32,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 4,
    marginBottom: 25,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 25,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1e293b",
  },
  chartWrapper: {
    marginBottom: 30,
  },
  statsGrid: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
    paddingTop: 20,
  },
  miniStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  miniIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  miniLabel: {
    fontSize: 11,
    color: "#64748b",
  },
  miniValue: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1e293b",
  },
  buttonContainer: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 35,
    paddingHorizontal: 4,
  },
  btn: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  btnPrimary: {
    backgroundColor: "#0284c7",
    flex: 1.4,
  },
  btnSecondary: {
    backgroundColor: "#e0f2fe",
  },
  btnOutline: {
    backgroundColor: "white",
    borderWidth: 1.5,
    borderColor: "#e2e8f0",
  },
  btnTextPrimary: {
    color: "white",
    fontWeight: "700",
    fontSize: 13,
  },
  btnTextSecondary: {
    color: "#0284c7",
    fontWeight: "700",
    fontSize: 13,
  },
  btnTextOutline: {
    color: "#64748b",
    fontWeight: "700",
    fontSize: 13,
  },
  sectionHeader: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1e293b",
  },
  themeCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 20,
    marginBottom: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  themeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  themeInfo: {
    flex: 1,
  },
  themeName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e293b",
  },
  themeDetail: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  themeBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  themeBadgeText: {
    fontSize: 14,
    fontWeight: "800",
  },
  progressContainer: {
    width: "100%",
  },
  progressTrack: {
    height: 10,
    backgroundColor: "#f1f5f9",
    borderRadius: 5,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 5,
  },
  recommendationBox: {
    backgroundColor: "#fff7ed",
    borderRadius: 24,
    padding: 24,
    borderLeftWidth: 5,
    borderLeftColor: "#f59e0b",
    marginTop: 10,
    marginBottom: 40,
  },
  recHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  recTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#9a3412",
  },
  recText: {
    fontSize: 14,
    color: "#9a3412",
    lineHeight: 22,
    fontWeight: "500",
  },
  reviewCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  reviewIndex: {
    fontSize: 14,
    fontWeight: "700",
    color: "#64748b",
  },
  statusTag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  statusTagText: {
    fontSize: 12,
    fontWeight: "800",
  },
  reviewQuestion: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e293b",
    lineHeight: 24,
    marginBottom: 20,
  },
  reviewOptions: {
    gap: 12,
    marginBottom: 20,
  },
  optRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    borderRadius: 14,
    borderWidth: 2,
    gap: 12,
  },
  optLetter: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
  },
  optLetterText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#64748b",
  },
  optText: {
    flex: 1,
    fontSize: 14,
    color: "#334155",
    fontWeight: "500",
  },
  feedbackTabsContainer: {
    flexDirection: "row",
    backgroundColor: "#f1f5f9",
    borderRadius: 14,
    padding: 4,
    marginTop: 18,
    marginBottom: 14,
    gap: 6,
  },
  feedbackTabItem: {
    flex: 1,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    gap: 6,
  },
  feedbackTabItemActive: {
    backgroundColor: "#ffffff",
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  feedbackTabText: {
    fontSize: 13.5,
    fontWeight: "600",
    color: "#64748b",
  },
  feedbackTabTextActive: {
    color: "#0f172a",
    fontWeight: "700",
  },
  explanationBox: {
    backgroundColor: "#f8fafc",
    borderRadius: 18,
    padding: 18,
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderLeftWidth: 4,
    borderLeftColor: "#0284c7",
  },
  explanationHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  explanationHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  explanationIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#e0f2fe",
    alignItems: "center",
    justifyContent: "center",
  },
  explanationTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
  },
  explanationBadge: {
    backgroundColor: "#dbeafe",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  explanationBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1d4ed8",
    letterSpacing: 0.5,
  },
  explanationText: {
    fontSize: 14,
    color: "#334155",
    lineHeight: 23,
    letterSpacing: 0.2,
    fontWeight: "400",
  },
  distractorBox: {
    backgroundColor: "#fffdfa",
    borderRadius: 18,
    padding: 18,
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#fed7aa",
    borderLeftWidth: 4,
    borderLeftColor: "#ea580c",
  },
  distractorHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  distractorHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  distractorIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#ffedd5",
    alignItems: "center",
    justifyContent: "center",
  },
  distractorTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
  },
  distractorBadge: {
    backgroundColor: "#fef3c7",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  distractorBadgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#b45309",
    letterSpacing: 0.5,
  },
  distractorText: {
    fontSize: 14,
    color: "#334155",
    lineHeight: 23,
    letterSpacing: 0.2,
    fontWeight: "400",
  },
  distractorList: {
    marginTop: 4,
    gap: 10,
  },
  distractorItemCard: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#fed7aa",
    shadowColor: "#ea580c",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  distractorItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 6,
  },
  distractorItemBadge: {
    width: 26,
    height: 26,
    borderRadius: 8,
    backgroundColor: "#fee2e2",
    borderWidth: 1,
    borderColor: "#fca5a5",
    alignItems: "center",
    justifyContent: "center",
  },
  distractorItemBadgeText: {
    fontSize: 13,
    fontWeight: "800",
    color: "#dc2626",
  },
  distractorItemLabel: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#0f172a",
    flex: 1,
  },
  distractorItemBody: {
    fontSize: 13.5,
    color: "#334155",
    lineHeight: 21,
    fontWeight: "400",
  },
  referenceBox: {
    backgroundColor: "#f5f3ff",
    borderRadius: 14,
    padding: 14,
    marginTop: 14,
    borderWidth: 1,
    borderColor: "#ddd6fe",
    borderLeftWidth: 3,
    borderLeftColor: "#7c3aed",
  },
  referenceHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  referenceTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#6d28d9",
  },
  referenceText: {
    fontSize: 13,
    color: "#475569",
    lineHeight: 20,
    fontStyle: "italic",
  },
  examenTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1e293b",
  },
  examenSubtitle: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 4,
  },
  summaryCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 20,
    marginBottom: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  summaryGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  summaryMetric: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  summaryIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  summaryMetricLabel: {
    fontSize: 12,
    color: "#64748b",
  },
  summaryMetricValue: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1e293b",
    marginTop: 2,
  },
  summaryDivider: {
    height: 1,
    backgroundColor: "#f1f5f9",
    marginBottom: 10,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f8fafc",
  },
  summaryRowLabel: {
    fontSize: 14,
    color: "#64748b",
    fontWeight: "500",
  },
  summaryRowValue: {
    fontSize: 14,
    color: "#1e293b",
    fontWeight: "700",
    maxWidth: "55%",
    textAlign: "right",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  statusBadgeText: {
    fontSize: 13,
    fontWeight: "800",
  },
});
