import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    backgroundColor: "white",
  },
  backBtn: {
    padding: 4,
  },
  headerTitleWrap: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1e293b",
  },
  headerSubtitle: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  tabsWrapper: {
    flexDirection: "row",
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingBottom: 10,
    gap: 12,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: "center",
    backgroundColor: "#f1f5f9",
  },
  tabBtnActive: {
    backgroundColor: "#0284c7",
  },
  tabBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#64748b",
  },
  tabBtnTextActive: {
    color: "white",
  },
  tabContent: {
    flex: 1,
    padding: 20,
  },
  mainCard: {
    backgroundColor: "white",
    borderRadius: 32,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 4,
    marginBottom: 25,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 25,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#1e293b",
  },
  chartWrapper: {
    marginBottom: 30,
  },
  statsGrid: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
    paddingTop: 20,
  },
  miniStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  miniIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  miniLabel: {
    fontSize: 12,
    color: "#64748b",
  },
  miniValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1e293b",
  },
  buttonContainer: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 35,
    paddingHorizontal: 4,
  },
  btn: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  btnPrimary: {
    backgroundColor: "#0284c7",
    flex: 1.4,
  },
  btnSecondary: {
    backgroundColor: "#e0f2fe",
  },
  btnOutline: {
    backgroundColor: "white",
    borderWidth: 1.5,
    borderColor: "#e2e8f0",
  },
  btnTextPrimary: {
    color: "white",
    fontWeight: "700",
    fontSize: 13,
  },
  btnTextSecondary: {
    color: "#0284c7",
    fontWeight: "700",
    fontSize: 13,
  },
  btnTextOutline: {
    color: "#64748b",
    fontWeight: "700",
    fontSize: 13,
  },
  sectionHeader: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1e293b",
  },
  themeCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 20,
    marginBottom: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  themeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  themeInfo: {
    flex: 1,
  },
  themeName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e293b",
  },
  themeDetail: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  themeBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  themeBadgeText: {
    fontSize: 14,
    fontWeight: "800",
  },
  progressContainer: {
    width: "100%",
  },
  progressTrack: {
    height: 10,
    backgroundColor: "#f1f5f9",
    borderRadius: 5,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 5,
  },
  recommendationBox: {
    backgroundColor: "#fff7ed",
    borderRadius: 24,
    padding: 24,
    borderLeftWidth: 5,
    borderLeftColor: "#f59e0b",
    marginTop: 10,
    marginBottom: 40,
  },
  recHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  recTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#9a3412",
  },
  recText: {
    fontSize: 14,
    color: "#9a3412",
    lineHeight: 22,
    fontWeight: "500",
  },
  reviewCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  reviewIndex: {
    fontSize: 14,
    fontWeight: "700",
    color: "#64748b",
  },
  statusTag: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  statusTagText: {
    fontSize: 12,
    fontWeight: "800",
  },
  reviewQuestion: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e293b",
    lineHeight: 24,
    marginBottom: 20,
  },
  reviewOptions: {
    gap: 12,
    marginBottom: 20,
  },
  optRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    borderRadius: 14,
    borderWidth: 2,
    gap: 12,
  },
  optLetter: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
  },
  optLetterText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#64748b",
  },
  optText: {
    flex: 1,
    fontSize: 14,
    color: "#334155",
    fontWeight: "500",
  },
  explanationBox: {
    backgroundColor: "#f0f9ff",
    borderRadius: 16,
    padding: 16,
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#e0f2fe",
  },
  explanationHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  explanationTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#0369a1",
  },
  explanationText: {
    fontSize: 13,
    color: "#0369a1",
    lineHeight: 18,
    fontWeight: "500",
  },
  examenTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1e293b",
  },
  examenSubtitle: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 4,
  },
});
