export const enum TagTypes {
  Profile = 'Profile',
  Area = 'Area',
  ExamType = 'ExamType',
  Specialty = 'Specialty',
  Theme = 'Theme',
  Year = 'Year',
  Question = 'Question',
  QuestionByTheme='QuestionByTheme',
  Ranking='Ranking',
  History='History',
  ExamHistory='ExamHistory',
  ChangePassword='ChangePassword',
  Support='Support',
  Student='Student',
  Doctor='Doctor',
  DoctorAvailability='DoctorAvailability',
  SmartReviewThemes='SmartReviewThemes',
  SmartReviewBlocks='SmartReviewBlocks',
  SmartReviewDue='SmartReviewDue',
}
