import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 50,
    paddingBottom: 15,
    paddingHorizontal: 20,
    backgroundColor: "white",
  },
  backBtn: {
    padding: 4,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1e293b",
  },
  tabNav: {
    flexDirection: "row",
    backgroundColor: "white",
    paddingHorizontal: 20,
    paddingBottom: 10,
    gap: 8,
  },
  tabItem: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#f1f5f9",
  },
  tabItemActive: {
    backgroundColor: "#0284c7",
  },
  tabItemText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#64748b",
  },
  tabItemTextActive: {
    color: "white",
  },
  tabContent: {
    flex: 1,
    padding: 20,
  },
  tabContentFlat: {
    flex: 1,
  },
  heroCard: {
    backgroundColor: "white",
    borderRadius: 32,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 20,
    elevation: 4,
    marginBottom: 20,
  },
  heroHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 25,
    width: "100%",
  },
  heroTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#64748b",
  },
  heroTheme: {
    fontSize: 14,
    color: "#1e293b",
    marginTop: 2,
  },
  heroMain: {
    alignItems: "center",
    marginBottom: 25,
  },
  heroInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    width: "100%",
  },
  heroInfoItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  heroInfoLabel: {
    fontSize: 12,
    color: "#64748b",
  },
  heroInfoValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1e293b",
  },
  heroInfoDivider: {
    width: 1,
    height: 30,
    backgroundColor: "#e2e8f0",
  },
  heroScore: {
    fontSize: 36,
    fontWeight: "800",
    color: "#1e293b",
  },
  heroScoreLabel: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 2,
  },
  heroStats: {
    flexDirection: "row",
    gap: 30,
    marginTop: 20,
  },
  heroStat: {
    alignItems: "center",
  },
  heroStatValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1e293b",
  },
  heroStatLabel: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  historySection: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: 12,
  },
  historyList: {
    gap: 12,
  },
  historyItemCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 2,
    borderColor: "transparent",
  },
  historyItemCardSelected: {
    borderColor: "#0284c7",
    backgroundColor: "#f0f9ff",
  },
  historyIndicator: {
    width: 4,
    height: 32,
    borderRadius: 2,
    marginRight: 12,
  },
  historyItemInfo: {
    flex: 1,
  },
  historyItemTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1e293b",
  },
  historyItemDate: {
    fontSize: 12,
    color: "#94a3b8",
    marginTop: 2,
  },
  historyItemScore: {
    alignItems: "flex-end",
  },
  historyScoreText: {
    fontSize: 16,
    fontWeight: "800",
  },
  reviewCard: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 20,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 10,
    elevation: 2,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  reviewIndex: {
    fontSize: 14,
    fontWeight: "700",
    color: "#64748b",
  },
  statusTag: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  statusTagText: {
    fontSize: 12,
    fontWeight: "800",
  },
  reviewQuestion: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e293b",
    lineHeight: 24,
    marginBottom: 20,
  },
  reviewOptions: {
    gap: 10,
    marginBottom: 15,
  },
  optRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 14,
    borderWidth: 2,
    gap: 12,
  },
  optLetter: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
  },
  optLetterText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#64748b",
  },
  optText: {
    flex: 1,
    fontSize: 14,
    color: "#334155",
    fontWeight: "500",
  },
  explanationBox: {
    backgroundColor: "#f0f9ff",
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e0f2fe",
  },
  explanationHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 6,
  },
  explanationTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#0369a1",
  },
  explanationText: {
    fontSize: 13,
    color: "#0369a1",
    lineHeight: 18,
    fontWeight: "500",
  },
  examenTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1e293b",
  },
  examenSubtitle: {
    fontSize: 14,
    color: "#64748b",
    marginTop: 4,
  },
  analysisCard: {
    backgroundColor: "white",
    borderRadius: 32,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.03,
    shadowRadius: 15,
    elevation: 3,
  },
  analysisHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 25,
  },
  analysisTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1e293b",
  },
  analysisSubtitle: {
    fontSize: 14,
    color: "#64748b",
  },
  orderedRecBox: {
    backgroundColor: "#f8fafc",
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    marginBottom: 25,
  },
  recTitleSmall: {
    fontSize: 12,
    fontWeight: "900",
    color: "#64748b",
    letterSpacing: 1,
    marginBottom: 15,
  },
  bulletItem: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 15,
  },
  bulletText: {
    fontSize: 14,
    color: "#334155",
    lineHeight: 22,
    fontWeight: "500",
    textAlign: "justify",
    flex: 1,
  },
  metricGridSmall: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
    paddingTop: 20,
  },
  metricMini: {
    alignItems: "center",
    flex: 1,
  },
  miniLabel: {
    fontSize: 11,
    color: "#64748b",
    fontWeight: "700",
    marginBottom: 4,
  },
  miniVal: {
    fontSize: 15,
    fontWeight: "800",
    color: "#1e293b",
  },
  retryButton: {
    backgroundColor: "#0284c7",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
    borderRadius: 20,
    marginTop: 10,
    marginBottom: 20,
    shadowColor: "#0284c7",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  retryButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
  },
});
