import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    padding: 20,
    paddingTop: 35,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  notification: {
    padding: 8,
  },
  greeting: {
    fontSize: 14,
  },
  username: {
    fontSize: 20,
    fontWeight: "bold",
  },
  aiCard: {
    backgroundColor: "#0f4c81",
    padding: 20,
    borderRadius: 20,
    marginBottom: 20,
  },
  aiLabel: {
    color: "#93c5fd",
    fontSize: 12,
    marginBottom: 5,
  },
  aiTitle: {
    color: "white",
    fontSize: 18,
    fontWeight: "bold",
  },
  aiText: {
    color: "#cbd5f5",
  },
  aiTopic: {
    color: "white",
    fontWeight: "600",
    marginBottom: 15,
  },
  aiButton: {
    backgroundColor: "white",
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
  },
  aiButtonText: {
    color: "#0f4c81",
    fontWeight: "bold",
  },
  metricsContainer: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 20,
  },
  metricCard: {
    flex: 1,
    padding: 15,
    borderRadius: 15,
    alignItems: "center",
  },
  metricNumber: {
    fontSize: 18,
    fontWeight: "bold",
    marginTop: 5,
  },
  metricLabel: {
    fontSize: 12,
  },
  calendarSection: {
    marginBottom: 20,
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  calendarTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  calendarTitle: {
    fontSize: 20,
    fontWeight: "800",
  },
  progressHeader: {
    backgroundColor: "#0284c7",
    borderRadius: 24,
    padding: 28,
    marginBottom: 18,
    shadowColor: "#0284c7",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  progressTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "white",
    marginBottom: 4,
  },
  progressSubtitle: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.85)",
    marginBottom: 20,
  },
  progressBarContainer: {
    height: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 10,
    overflow: "hidden",
  },
  progressBar: {
    height: "100%",
    borderRadius: 10,
  },
  progressStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
  },
  progressStat: {
    fontSize: 15,
    fontWeight: "700",
    color: "white",
  },
  calendarList: {
    gap: 12,
  },
  loadingContainer: {
    padding: 20,
    alignItems: "center",
    gap: 10,
  },
  loadingText: {
    fontSize: 14,
  },
  emptyContainer: {
    padding: 22,
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 18,
  },
  emptyTitle: { fontSize: 16, fontWeight: "800", marginBottom: 6 },
  emptyText: {
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  retryButton: { marginTop: 16, minHeight: 44, paddingHorizontal: 18, borderRadius: 12, backgroundColor: "#0284c7", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  retryButtonDisabled: { opacity: 0.7 },
  retryButtonText: { color: "#ffffff", fontSize: 14, fontWeight: "800" },
  dayCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 18,
    minHeight: 88,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  dayCardToday: {
    borderColor: "#0284c7",
    borderWidth: 1.5,
    shadowColor: "#0284c7",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 3,
  },
  dayCardPressed: {
    backgroundColor: "#e0f2fe",
    borderColor: "#0284c7",
    transform: [{ scale: 0.99 }],
  },
  dayDateBadge: {
    width: 54,
    height: 62,
    borderRadius: 15,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  dayDateBadgeToday: { backgroundColor: "#0284c7" },
  dayIconContainer: {
    width: 30,
    height: 30,
    borderRadius: 9,
    justifyContent: "center",
    alignItems: "center",
  },
  dayContent: {
    flex: 1,
    marginHorizontal: 12,
  },
  daySubjectRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 7,
  },
  dayText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#64748b",
    letterSpacing: 0.6,
  },
  dayTextToday: { color: "rgba(255,255,255,0.85)" },
  dayDateNumber: { color: "#0f172a", fontSize: 24, lineHeight: 28, fontWeight: "800" },
  dayDateNumberToday: { color: "#ffffff" },
  daySubject: {
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    color: "#334155",
  },
  dayMetaRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 5 },
  dayMetaText: { fontSize: 11, fontWeight: "600" },
  dayProgressText: { fontSize: 11, fontWeight: "800" },
  dayProgressTrack: { height: 5, borderRadius: 3, backgroundColor: "#e2e8f0", overflow: "hidden" },
  dayProgressFill: { height: "100%", borderRadius: 3 },
});
