import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 50,
    paddingBottom: 12,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1e293b",
  },
  listHeader: {
    paddingBottom: 4,
  },
  listContent: {
    paddingBottom: 104,
  },
  selectedInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#dbeafe",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 4,
  },
  selectedText: {
    color: "#0369a1",
    fontSize: 14,
    fontWeight: "700",
  },
  multiDownloadButton: {
    backgroundColor: "#0284c7",
    borderRadius: 12,
    padding: 10,
    shadowColor: "#0284c7",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1e293b",
    marginHorizontal: 16,
    marginBottom: 14,
    marginTop: 18,
    letterSpacing: -0.3,
  },
  examCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 16,
    padding: 14,
    marginHorizontal: 16,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 2,
    borderColor: "transparent",
  },
  dateSectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    marginHorizontal: 16,
    marginBottom: 14,
    marginTop: 12,
    letterSpacing: -0.3,
  },
  examCardSelected: {
    borderColor: "#0284c7",
    backgroundColor: "#f0f9ff",
  },
  checkboxContainer: {
    marginRight: 10,
  },
  checkbox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#cbd5e1",
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxChecked: {
    backgroundColor: "#0284c7",
    borderColor: "#0284c7",
  },
  examIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#dbeafe",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  examInfo: {
    flex: 1,
  },
  examTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1e293b",
    marginBottom: 2,
  },
  examMeta: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "500",
  },
  examDate: {
    fontSize: 11,
    fontWeight: "600",
    marginTop: 4,
  },
  downloadedBadge: {
    backgroundColor: "#dcfce7",
    borderRadius: 12,
    padding: 10,
  },
  downloadIconButton: {
    backgroundColor: "#dbeafe",
    borderRadius: 12,
    padding: 10,
  },
  downloadBar: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 12,
    minHeight: 72,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 8,
  },
  downloadBarTitle: {
    fontSize: 14,
    fontWeight: "800",
  },
  downloadBarCount: {
    fontSize: 12,
    fontWeight: "500",
    marginTop: 2,
  },
  downloadBarButton: {
    minWidth: 126,
    height: 44,
    borderRadius: 12,
    paddingHorizontal: 16,
    backgroundColor: "#0284c7",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  downloadBarButtonText: {
    color: "white",
    fontSize: 13,
    fontWeight: "800",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#64748b",
    marginTop: 10,
  },
  emptyContainer: {
    padding: 40,
    alignItems: "center",
  },
  emptyText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#64748b",
  },
  pagination: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
  },
  paginationButton: {
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: "rgba(2, 132, 199, 0.08)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  paginationButtonDisabled: {
    opacity: 0.4,
  },
  paginationButtonText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#0284c7",
  },
  paginationIndicator: {
    fontSize: 13,
    fontWeight: "600",
  },
});
